services:
  mc:
    image: masnypen/serweron
    container_name: test-mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      VERSION: "1.21"
    volumes:
      - ./server:/data
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


